apiVersion: v1
kind: Template
metadata:
  name: Template
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: ${APP_NAME}
    namespace: ${NAMESPACE_NAME}
  spec:
    lookupPolicy:
      local: false
    tags:
      - annotations: null
        from:
          kind: DockerImage
          name: ${REGISTRY_PATH}
        importPolicy: {}
        name: latest
        referencePolicy:
          type: Source
parameters:
- name: APP_NAME
- name: NAMESPACE_NAME
- name: REGISTRY_PATH