apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: tech-dsometr
  namespace: tech-nexign-sbx
spec:
  lookupPolicy:
    local: false
  tags:
    - annotations: null
      from:
        kind: DockerImage
        name: 'registry.dso.techpark.local/tech-dsometr:latest'
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source