apiVersion: template.openshift.io/v1    
kind: Template
labels:
  app: ${APP_NAME}
  template: ${APP_NAME}-template
metadata:
  annotations:
    description: ${APP_NAME} Frontend service
    openshift.io/display-name: ${APP_NAME}
    openshift.io/provider-display-name: ${APP_NAME}
    tags: ${APP_NAME}
  name: ${APP_NAME}
objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: ${APP_NAME}
      name: ${APP_NAME}
      namespace: ${NAMESPACE_NAME}
    spec:
      replicas: 1
      strategy:
        activeDeadlineSeconds: 21600
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          labels:
            app: ${APP_NAME}
            deploymentconfig: ${APP_NAME}
        name: ${APP_NAME}-pod
        spec:
          containers:
            - env:
              imagePullPolicy: Always
              livenessProbe:
                failureThreshold: 3
                httpGet:
                  path: /
                  port: 8080
                  scheme: HTTP
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
              name: ${APP_NAME}
              ports:
                - containerPort: 8080
                  protocol: TCP
              readinessProbe:
                failureThreshold: 3
                httpGet:
                  path: /index.html
                  port: 8080
                  scheme: HTTP
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
              resources: {}
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
      triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
              - ${APP_NAME}
            from:
              kind: ImageStreamTag
              name: '${APP_NAME}:latest'
              namespace: ${NAMESPACE_NAME}
          type: ImageChange
  - apiVersion: v1
    kind: Service
    metadata:
      name: ${APP_NAME}
      labels:
        app: ${APP_NAME}
    spec:
      type: ClusterIP
      ports:
      - port: 8080
        protocol: TCP
        targetPort: 8080
      selector:
        app: ${APP_NAME}
  - apiVersion: v1
    kind: Route
    metadata:
      name: ${APP_NAME}
      annotations:
        haproxy.router.openshift.io/timeout: 4m
    spec:
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: ${APP_NAME}
parameters:
- name: APP_NAME
- name: NAMESPACE_NAME