apiVersion: template.openshift.io/v1    
kind: Template
labels:
  app: tech-dsometr
  template: tech-dsometr-template
metadata:
  annotations:
    description: tech-dsometr Frontend service
    openshift.io/display-name: tech-dsometr
    openshift.io/provider-display-name: tech-dsometr
    tags: tech-dsometr
  name: tech-dsometr
objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: tech-dsometr
      name: tech-dsometr
      namespace: tech-nexign-sbx
    spec:
      replicas: 1
      strategy:
        activeDeadlineSeconds: 21600
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          labels:
            app: tech-dsometr
            deploymentconfig: tech-dsometr
        name: tech-dsometr-pod
        spec:
          containers:
            - env:
              imagePullPolicy: Always
              livenessProbe:
                failureThreshold: 3
                httpGet:
                  path: /
                  port: 8080
                  scheme: HTTP
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
              name: tech-dsometr
              ports:
                - containerPort: 8080
                  protocol: TCP
              readinessProbe:
                failureThreshold: 3
                httpGet:
                  path: /index.html
                  port: 8080
                  scheme: HTTP
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
              resources: {}
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
      triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
              - tech-dsometr
            from:
              kind: ImageStreamTag
              name: 'tech-dsometr:latest'
              namespace: tech-nexign-sbx
          type: ImageChange
  - apiVersion: v1
    kind: Service
    metadata:
      name: tech-dsometr
      labels:
        app: tech-dsometr
    spec:
      type: ClusterIP
      ports:
      - port: 8080
        protocol: TCP
        targetPort: 8080
      selector:
        app: tech-dsometr
  - apiVersion: v1
    kind: Route
    metadata:
      name: tech-dsometr
      annotations:
        haproxy.router.openshift.io/timeout: 4m
    spec:
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: tech-dsometr